### ISSUE TITLE
undefined method `empty?' for nil:NilClass in `private_api/proteins`

### ISSUE THREAD

**Issue by pverscha** [unipept/unipept#1026]
An exception `undefined method `empty?' for nil:NilClass` sometimes occurs in the `private_api/proteins`-endpoint. Full stacktrace of the exception:

```
A NoMethodError occurred in private_api#proteins:

  undefined method `empty?' for nil:NilClass
  app/models/lineage.rb:147:in `calculate_lca'
  app/models/lineage.rb:141:in `calculate_lca_taxon'
  app/controllers/private_api_controller.rb:76:in `proteins'

Parameters : {"peptide"=>"DWENPGVTQLNRLAAHPPFASWRNSEEARTDR", "equateIl"=>true, "controller"=>"private_api", "action"=>"proteins", "private_api"=>{"peptide"=>"DWENPGVTQLNRLAAHPPFASWRNSEEARTDR", "equateIl"=>true}, "format"=>"json"}
```

**Comment by pverscha** [comment]
Fixed in #1027
