### ISSUE TITLE
order output columns as specified with the --select option

### ISSUE THREAD

**Issue by bmesuere** [unipept/unipept#220]
here are some issues:

```
$ echo -ne "1\n816\n816\n" | unipept taxa2lca -s taxon_name -s taxon_id
taxon_id,taxon_name
816,Bacteroides
$ echo -ne "1\n816\n816\n" | unipept taxa2lca -s taxon_*

/users/p/pdawyndt/.gem/ruby/1.9.1/gems/unipept-0.3.2/lib/unipept/formatters.rb:68:in `block (2 levels) in format': undefined method `values' for nil:NilClass (NoMethodError)
        from /users/p/pdawyndt/.gem/ruby/1.9.1/gems/unipept-0.3.2/lib/unipept/formatters.rb:64:in `each'
        from /users/p/pdawyndt/.gem/ruby/1.9.1/gems/unipept-0.3.2/lib/unipept/formatters.rb:64:in `block in format'
        from /usr/lib/ruby/1.9.1/csv.rb:1243:in `generate'
        from /users/p/pdawyndt/.gem/ruby/1.9.1/gems/unipept-0.3.2/lib/unipept/formatters.rb:63:in `format'
        from /users/p/pdawyndt/.gem/ruby/1.9.1/gems/unipept-0.3.2/bin/unipept:111:in `block (3 levels) in run'
        from /users/p/pdawyndt/.gem/ruby/1.9.1/gems/unipept-0.3.2/lib/unipept/batch_order.rb:15:in `call'
        from /users/p/pdawyndt/.gem/ruby/1.9.1/gems/unipept-0.3.2/lib/unipept/batch_order.rb:15:in `wait'
        from /users/p/pdawyndt/.gem/ruby/1.9.1/gems/unipept-0.3.2/bin/unipept:106:in `block (2 levels) in run'
        from /users/p/pdawyndt/.gem/ruby/1.9.1/gems/typhoeus-0.6.8/lib/typhoeus/request/callbacks.rb:129:in `call'
        from /users/p/pdawyndt/.gem/ruby/1.9.1/gems/typhoeus-0.6.8/lib/typhoeus/request/callbacks.rb:129:in `block in execute_callbacks'
        from /users/p/pdawyndt/.gem/ruby/1.9.1/gems/typhoeus-0.6.8/lib/typhoeus/request/callbacks.rb:128:in `map'
        from /users/p/pdawyndt/.gem/ruby/1.9.1/gems/typhoeus-0.6.8/lib/typhoeus/request/callbacks.rb:128:in `execute_callbacks'
        from /users/p/pdawyndt/.gem/ruby/1.9.1/gems/typhoeus-0.6.8/lib/typhoeus/request/operations.rb:35:in `finish'
        from /users/p/pdawyndt/.gem/ruby/1.9.1/gems/typhoeus-0.6.8/lib/typhoeus/easy_factory.rb:105:in `block in set_callback'
        from /users/p/pdawyndt/.gem/ruby/1.9.1/gems/ethon-0.7.0/lib/ethon/easy/response_callbacks.rb:65:in `call'
        from /users/p/pdawyndt/.gem/ruby/1.9.1/gems/ethon-0.7.0/lib/ethon/easy/response_callbacks.rb:65:in `block in complete'
        from /users/p/pdawyndt/.gem/ruby/1.9.1/gems/ethon-0.7.0/lib/ethon/easy/response_callbacks.rb:65:in `each'
        from /users/p/pdawyndt/.gem/ruby/1.9.1/gems/ethon-0.7.0/lib/ethon/easy/response_callbacks.rb:65:in `complete'
        from /users/p/pdawyndt/.gem/ruby/1.9.1/gems/ethon-0.7.0/lib/ethon/multi/operations.rb:148:in `check'
        from /users/p/pdawyndt/.gem/ruby/1.9.1/gems/ethon-0.7.0/lib/ethon/multi/operations.rb:161:in `run'
        from /users/p/pdawyndt/.gem/ruby/1.9.1/gems/ethon-0.7.0/lib/ethon/multi/operations.rb:43:in `perform'
        from /users/p/pdawyndt/.gem/ruby/1.9.1/gems/typhoeus-0.6.8/lib/typhoeus/hydra/runnable.rb:21:in `run'
        from /users/p/pdawyndt/.gem/ruby/1.9.1/gems/typhoeus-0.6.8/lib/typhoeus/hydra/memoizable.rb:51:in `run'
        from /users/p/pdawyndt/.gem/ruby/1.9.1/gems/unipept-0.3.2/bin/unipept:131:in `run'
        from /users/p/pdawyndt/.gem/ruby/1.9.1/gems/cri-2.6.0/lib/cri/command_runner.rb:36:in `call'
        from /users/p/pdawyndt/.gem/ruby/1.9.1/gems/cri-2.6.0/lib/cri/command_dsl.rb:223:in `block in runner'
        from /users/p/pdawyndt/.gem/ruby/1.9.1/gems/cri-2.6.0/lib/cri/command.rb:298:in `call'
        from /users/p/pdawyndt/.gem/ruby/1.9.1/gems/cri-2.6.0/lib/cri/command.rb:298:in `run_this'
        from /users/p/pdawyndt/.gem/ruby/1.9.1/gems/cri-2.6.0/lib/cri/command.rb:251:in `run'
        from /users/p/pdawyndt/.gem/ruby/1.9.1/gems/cri-2.6.0/lib/cri/command.rb:264:in `run'
        from /users/p/pdawyndt/.gem/ruby/1.9.1/gems/unipept-0.3.2/bin/unipept:302:in `<top (required)>'
        from /users/p/pdawyndt/.gem/ruby/1.9.1/bin/unipept:19:in `load'
        from /users/p/pdawyndt/.gem/ruby/1.9.1/bin/unipept:19:in `<main>'
```

In the first command, I would like to force the name to be output first, then the ID. In the second example I want to use wildcards to include a whole series of fields at once.

_[Original issue](https://github.ugent.be/unipept/unipept/issues/220) by ghost on Tue Mar 18 2014 at 10:17._
_Closed by @bmesuere on Wed May 20 2015 at 18:53._

**Comment by bmesuere** [comment]
Split into separate issues unipept/unipept-cli#33 and unipept/unipept-cli#34


_[Original comment](https://github.ugent.be/unipept/unipept/issues/220#issuecomment-18125) by @bmesuere on Wed May 20 2015 at 18:53._
