### ISSUE TITLE
taxa2lca: error

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#275]
```
$ fasta2prot < patient_TS19_CDS | sed -ne '10{p;q}' | prot2pept | peptfilter | sed -ne '2{p;q}' | unipept pept2prot | awk -F, '{print $3}' | tail -n +2 | unipept taxa2lca
API request failed! log can be found in /users/p/pdawyndt/unipept.log
```

_[Original issue](https://github.ugent.be/unipept/unipept/issues/275) by @pdawyndt on Tue May 06 2014 at 09:33._
_Closed by @bmesuere on Wed May 07 2014 at 14:25._

**Comment by pdawyndt** [comment]
got new error when I ran the command on helios

```
$ fasta2prot < patient_TS19_CDS | sed -ne '10{p;q}' | prot2pept | peptfilter | sed -ne '2{p;q}' | unipept pept2prot | awk -F, '{print $3}' | tail -n +2 | unipept taxa2lca
/users/p/pdawyndt/.gem/ruby/1.9.1/gems/unipept-0.3.1/bin/unipept:184:in `peptide_iterator': undefined method `call' for nil:NilClass (NoMethodError)
        from /users/p/pdawyndt/.gem/ruby/1.9.1/gems/unipept-0.3.1/bin/unipept:81:in `run'
        from /users/p/pdawyndt/.gem/ruby/1.9.1/gems/cri-2.6.0/lib/cri/command_runner.rb:36:in `call'
        from /users/p/pdawyndt/.gem/ruby/1.9.1/gems/cri-2.6.0/lib/cri/command_dsl.rb:223:in `block in runner'
        from /users/p/pdawyndt/.gem/ruby/1.9.1/gems/cri-2.6.0/lib/cri/command.rb:298:in `call'
        from /users/p/pdawyndt/.gem/ruby/1.9.1/gems/cri-2.6.0/lib/cri/command.rb:298:in `run_this'
        from /users/p/pdawyndt/.gem/ruby/1.9.1/gems/cri-2.6.0/lib/cri/command.rb:251:in `run'
        from /users/p/pdawyndt/.gem/ruby/1.9.1/gems/cri-2.6.0/lib/cri/command.rb:264:in `run'
        from /users/p/pdawyndt/.gem/ruby/1.9.1/gems/unipept-0.3.1/bin/unipept:301:in `<top (required)>'
        from /users/p/pdawyndt/.gem/ruby/1.9.1/bin/unipept:19:in `load'
        from /users/p/pdawyndt/.gem/ruby/1.9.1/bin/unipept:19:in `<main>'
```


_[Original comment](https://github.ugent.be/unipept/unipept/issues/275#issuecomment-9281) by @pdawyndt on Tue May 06 2014 at 20:44._

**Comment by pdawyndt** [comment]
Here's another use case that also produced the same error, but where it would be handy to have access to the command:

```
$ fasta2prot < patient_TS19_CDS | sed -ne '10{p;q}' | prot2pept | peptfilter | unipept pept2prot -e | tail -n +2 | awk -F, '{print $2}' | sort | uniq -c | sort -k1,1nr -k2,2 | awk '$1 >= 2 {print $2}' | uniprot2taxa | sort | uniq
408170
469586
469590
469591
469592
483217
563193
658661
702443
709991
742817
997873
997880
997881
997882
997883
997885
997889
997890
999420
```

Here I lookup all Uniprot proteins that at least two contain two peptides from the input protein. From these proteins I lookup the taxon IDs (using an additional script `uniprot2taxa`  while waiting for the extensions of the uniprot command where also the `taxon_id` would be ideally included in the output). If I now want to compute the LCA for these taxa, the `unipept taxa2lca command` crashes

```
$ fasta2prot < patient_TS19_CDS | sed -ne '10{p;q}' | prot2pept | peptfilter | unipept pept2prot -e | tail -n +2 | awk -F, '{print $2}' | sort | uniq -c | sort -k1,1nr -k2,2 | awk '$1 >= 2 {print $2}' | uniprot2taxa | sort | uniq | unipept taxa2lca
/users/p/pdawyndt/.gem/ruby/1.9.1/gems/unipept-0.3.1/bin/unipept:184:in `peptide_iterator': undefined method `call' for nil:NilClass (NoMethodError)
        from /users/p/pdawyndt/.gem/ruby/1.9.1/gems/unipept-0.3.1/bin/unipept:81:in `run'
        from /users/p/pdawyndt/.gem/ruby/1.9.1/gems/cri-2.6.0/lib/cri/command_runner.rb:36:in `call'
        from /users/p/pdawyndt/.gem/ruby/1.9.1/gems/cri-2.6.0/lib/cri/command_dsl.rb:223:in `block in runner'
        from /users/p/pdawyndt/.gem/ruby/1.9.1/gems/cri-2.6.0/lib/cri/command.rb:298:in `call'
        from /users/p/pdawyndt/.gem/ruby/1.9.1/gems/cri-2.6.0/lib/cri/command.rb:298:in `run_this'
        from /users/p/pdawyndt/.gem/ruby/1.9.1/gems/cri-2.6.0/lib/cri/command.rb:251:in `run'
        from /users/p/pdawyndt/.gem/ruby/1.9.1/gems/cri-2.6.0/lib/cri/command.rb:264:in `run'
        from /users/p/pdawyndt/.gem/ruby/1.9.1/gems/unipept-0.3.1/bin/unipept:301:in `<top (required)>'
        from /users/p/pdawyndt/.gem/ruby/1.9.1/bin/unipept:19:in `load'
        from /users/p/pdawyndt/.gem/ruby/1.9.1/bin/unipept:19:in `<main>'
```


_[Original comment](https://github.ugent.be/unipept/unipept/issues/275#issuecomment-9297) by @pdawyndt on Wed May 07 2014 at 11:42._
