### ISSUE TITLE
error on calculating LCA of empty bioprojectid list

### ISSUE THREAD

**Issue by bmesuere** [unipept/unipept#369]
> An ActiveRecord::StatementInvalid occurred in peptidome#get_lca:
> 
>  Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AND genomes.taxon_id is not null' at line 1: SELECT lineages.\* from genomes LEFT JOIN lineages ON genomes.taxon_id = lineages.taxon_id WHERE bioproject_id IN () AND genomes.taxon_id is not null
>  app/controllers/peptidome_controller.rb:68:in `get_lca'
> 
> ---
> 
> ## Request:
> - URL        : http://scruffy.ugent.be/peptidome/get_lca
> - HTTP Method: POST
> - IP address : 157.193.163.140
> - Parameters : {"bioprojects"=>"", "controller"=>"peptidome", "action"=>"get_lca"}
> - Timestamp  : 2014-06-11 07:46:20 UTC
> - Server : scruffy
> - Rails root : /home/bmesuere/rails/releases/20140608125118
> - Process: 12117
> 
> ---
> 
> ## Session:
> - session id: nil
> - data: {}
> 
> ---
> 
> ## Environment:
> - CONTENT_LENGTH                                 : 12
> - CONTENT_TYPE                                   : application/x-www-form-urlencoded
> - DOCUMENT_ROOT                                  : /home/bmesuere/rails/current/public
> - HTTP_ACCEPT                                    : _/_
> - HTTP_ACCEPT_ENCODING                           : gzip,deflate,sdch
> - HTTP_ACCEPT_LANGUAGE                           : nl-NL,nl;q=0.8,en-US;q=0.6,en;q=0.4
> - HTTP_CONNECTION                                : keep-alive
> - HTTP_COOKIE                                    : __utma=194700969.1473719590.1333453777.1386667885.1393922159.194; __utmz=194700969.1386336580.191.99.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided); _ga=GA1.2.1473719590.1333453777; __utma=170842786.1473719590.1333453777.1399637243.1402471384.4; __utmb=170842786.26.9.1402472697878; __utmc=170842786; __utmz=170842786.1399448010.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); _unipept_web_session=QSt0NXVwYU5XRFBQcUc1RVhFK0RrZld5di9pR2JwSjhRbWFaRnZ6K0pFd1NwQU5ubkFHNEVreHk2R0JKYWcrcXZjeDQwWW52L2xQZE4zQ05NYkR4Tkk0RXJ5NnZxYmFxdWpWdURQQmpyakkyM3VIM1Njbng1SFRSM3NOU1RSQnJvTC93UEgvQmVuT1pjT1dxMWhwS0JDTXZzTzhNRExvUXNCbXo5Nkt2aG5BemhrbEEzSDZYekhWOFpzbG56R011LS1BZC9DRnJNVmorb0VoakNxLzRuam13PT0%3D--7467029657ea7d75740d75ebad52377512466cd9
> - HTTP_HOST                                      : scruffy.ugent.be
> - HTTP_ORIGIN                                    : http://scruffy.ugent.be
> - HTTP_REFERER                                   : http://scruffy.ugent.be/assets/workers/pancore_worker.js
> - HTTP_USER_AGENT                                : Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.114 Safari/537.36
> - ORIGINAL_FULLPATH                              : /peptidome/get_lca/
> - ORIGINAL_SCRIPT_NAME                           :
> - PASSENGER_APP_ENV                              : development
> - PASSENGER_APP_GROUP_NAME                       : /home/bmesuere/rails/current
> - PASSENGER_APP_ROOT                             : /home/bmesuere/rails/current
> - PASSENGER_APP_TYPE                             : rack
> - PASSENGER_CONNECT_PASSWORD                     : [FILTERED]
> - PASSENGER_DEBUGGER                             : false
> - PASSENGER_FRIENDLY_ERROR_PAGES                 : true
> - PASSENGER_MAX_PRELOADER_IDLE_TIME              : -1
> - PASSENGER_RESTART_DIR                          :
> - PASSENGER_RUBY                                 : /home/bmesuere/.rvm/gems/ruby-2.1.1/wrappers/ruby
> - PASSENGER_SHOW_VERSION_IN_HEADER               : true
> - PASSENGER_SPAWN_METHOD                         : smart
> - PASSENGER_STATUS_LINE                          : false
> - PASSENGER_STAT_THROTTLE_RATE                   : 0
> - PATH_INFO                                      : /peptidome/get_lca
> - QUERY_STRING                                   :
> - REMOTE_ADDR                                    : 157.193.163.140
> - REMOTE_PORT                                    : 49768
> - REQUEST_METHOD                                 : POST
> - REQUEST_URI                                    : /peptidome/get_lca/
> - ROUTES_30211860_SCRIPT_NAME                    :
> - SCRIPT_NAME                                    :
> - SERVER_ADDR                                    : 157.193.229.36
> - SERVER_ADMIN                                   : webmaster`@localhost`
> - SERVER_NAME                                    : scruffy.ugent.be
> - SERVER_PORT                                    : 80
> - SERVER_PROTOCOL                                : HTTP/1.1
> - SERVER_SOFTWARE                                : Apache/2.2.16 (Debian)
> - action_controller.instance                     : #PeptidomeController:0x00000001b3d2f0
> - action_dispatch.backtrace_cleaner              : #Rails::BacktraceCleaner:0x00000001555248
> - action_dispatch.cookies                        : #ActionController::RequestForgeryProtection::ProtectionMethods::NullSession::NullCookieJar:0x00000001c38060
> - action_dispatch.cookies_serializer             :
> - action_dispatch.encrypted_cookie_salt          : encrypted cookie
> - action_dispatch.encrypted_signed_cookie_salt   : signed encrypted cookie
> - action_dispatch.http_auth_salt                 : http authentication
> - action_dispatch.key_generator                  : #ActiveSupport::CachingKeyGenerator:0x00000001562510
> - action_dispatch.logger                         : #ActiveSupport::Logger:0x00000003824800
> - action_dispatch.parameter_filter               : [:password]
> - action_dispatch.redirect_filter                : []
> - action_dispatch.remote_ip                      : 157.193.163.140
> - action_dispatch.request.accepts                : [#<Mime::Type:0x00000003481900 `@synonyms`=[], `@symbol`=nil, `@string`="*/*">]
> - action_dispatch.request.content_type           : application/x-www-form-urlencoded
> - action_dispatch.request.flash_hash             :
> - action_dispatch.request.formats                : [#<Mime::Type:0x00000003481900 `@synonyms`=[], `@symbol`=nil, `@string`="*/*">]
> - action_dispatch.request.parameters             : {"bioprojects"=>"", "controller"=>"peptidome", "action"=>"get_lca"}
> - action_dispatch.request.path_parameters        : {:controller=>"peptidome", :action=>"get_lca"}
> - action_dispatch.request.query_parameters       : {}
> - action_dispatch.request.request_parameters     : {"bioprojects"=>""}
> - action_dispatch.request.unsigned_session_cookie: {"session_id"=>"2be7014d7f587089071ebaaa0d4d37ed"}
> - action_dispatch.request_id                     : 963e6433-3092-419a-84fd-889ee5c45348
> - action_dispatch.routes                         : #ActionDispatch::Routing::RouteSet:0x0000000399fe28
> - action_dispatch.secret_key_base                : 4f548bc8a0337c30fdcda10be3cb5b666e7a0a3bfa32bbafc2bdb766e02d7f8ee1ab2a017e2c5c00cbeed3aa29743ccf26caf777636c331292f8f5318a19f437
> - action_dispatch.secret_token                   :
> - action_dispatch.show_detailed_exceptions       : true
> - action_dispatch.show_exceptions                : true
> - action_dispatch.signed_cookie_salt             : signed cookie
> - devise.skip_storage                            : true
> - rack.errors                                    : #IO:0x00000001305c68
> - rack.hijack                                    : #<Proc:0x00000001701100@/home/bmesuere/.rvm/gems/ruby-2.1.1/gems/passenger-4.0.42/lib/phusion_passenger/rack/thread_handler_extension.rb:69 (lambda)>
> - rack.hijack?                                   : true
> - rack.input                                     : #PhusionPassenger::Utils::TeeInput:0x000000017020f0
> - rack.multiprocess                              : true
> - rack.multithread                               : false
> - rack.request.cookie_hash                       : {"__utma"=>"194700969.1473719590.1333453777.1386667885.1393922159.194", "__utmz"=>"194700969.1386336580.191.99.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not provided)", "_ga"=>"GA1.2.1473719590.1333453777", "__utmb"=>"170842786.26.9.1402472697878", "__utmc"=>"170842786", "_unipept_web_session"=>"QSt0NXVwYU5XRFBQcUc1RVhFK0RrZld5di9pR2JwSjhRbWFaRnZ6K0pFd1NwQU5ubkFHNEVreHk2R0JKYWcrcXZjeDQwWW52L2xQZE4zQ05NYkR4Tkk0RXJ5NnZxYmFxdWpWdURQQmpyakkyM3VIM1Njbng1SFRSM3NOU1RSQnJvTC93UEgvQmVuT1pjT1dxMWhwS0JDTXZzTzhNRExvUXNCbXo5Nkt2aG5BemhrbEEzSDZYekhWOFpzbG56R011LS1BZC9DRnJNVmorb0VoakNxLzRuam13PT0=--7467029657ea7d75740d75ebad52377512466cd9"}
> - rack.request.cookie_string                     : __utma=194700969.1473719590.1333453777.1386667885.1393922159.194; __utmz=194700969.1386336580.191.99.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided); _ga=GA1.2.1473719590.1333453777; __utma=170842786.1473719590.1333453777.1399637243.1402471384.4; __utmb=170842786.26.9.1402472697878; __utmc=170842786; __utmz=170842786.1399448010.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); _unipept_web_session=QSt0NXVwYU5XRFBQcUc1RVhFK0RrZld5di9pR2JwSjhRbWFaRnZ6K0pFd1NwQU5ubkFHNEVreHk2R0JKYWcrcXZjeDQwWW52L2xQZE4zQ05NYkR4Tkk0RXJ5NnZxYmFxdWpWdURQQmpyakkyM3VIM1Njbng1SFRSM3NOU1RSQnJvTC93UEgvQmVuT1pjT1dxMWhwS0JDTXZzTzhNRExvUXNCbXo5Nkt2aG5BemhrbEEzSDZYekhWOFpzbG56R011LS1BZC9DRnJNVmorb0VoakNxLzRuam13PT0%3D--7467029657ea7d75740d75ebad52377512466cd9
> - rack.request.form_hash                         : {"bioprojects"=>""}
> - rack.request.form_input                        : #PhusionPassenger::Utils::TeeInput:0x000000017020f0
> - rack.request.form_vars                         : [FILTERED]
> - rack.request.query_hash                        : {}
> - rack.request.query_string                      :
> - rack.run_once                                  : false
> - rack.session                                   : #ActionController::RequestForgeryProtection::ProtectionMethods::NullSession::NullSessionHash:0x00000001c38da8
> - rack.session.options                           : {:skip=>true}
> - rack.url_scheme                                : http
> - rack.version                                   : [1, 2]
> - warden                                         : Warden::Proxy:14220760 `@config`={:default_scope=>:user, :scope_defaults=>{}, :default_strategies=>{:user=>[:cas_authenticatable]}, :intercept_401=>false, :failure_app=>#Devise::Delegator:0x00000004b77858}
> 
> ---
> 
> ## Backtrace:
> 
>  app/controllers/peptidome_controller.rb:68:in `get_lca'

_[Original issue](https://github.ugent.be/unipept/unipept/issues/369) by @bmesuere on Wed Jun 11 2014 at 09:53._
_Closed by @bmesuere on Sat Jun 14 2014 at 19:16._

**Comment by bmesuere** [comment]
Occurs when you only add "mygenomes".


_[Original comment](https://github.ugent.be/unipept/unipept/issues/369#issuecomment-10056) by @bmesuere on Thu Jun 12 2014 at 17:19._
