### ISSUE TITLE
invalid PRIDE id should show exception to user

### ISSUE THREAD

**Issue by bmesuere** [unipept/unipept#456]
```
A NoMethodError occurred in pride#load:

  undefined method `map' for nil:NilClass
  app/controllers/pride_controller.rb:4:in `load'


-------------------------------
Request:
-------------------------------

  * URL        : http://unipept.ugent.be/pride/PXD000054
  * HTTP Method: GET
  * IP address : 195.178.203.184
  * Parameters : {"controller"=>"pride", "action"=>"load", "id"=>"PXD000054"}
  * Timestamp  : 2015-01-27 12:55:16 UTC
  * Server : sherlock
  * Rails root : /home/bmesuere/rails/releases/20150116093434
  * Process: 21490

-------------------------------
Session:
-------------------------------

  * session id: "68a7b8adcd3b95da7ace9680f4d633e6"
  * data: {"session_id"=>"68a7b8adcd3b95da7ace9680f4d633e6",
   "_csrf_token"=>"OBrVa1jDt9ojgauiPc92Ass+d67JNthk+Ilh86Ul1qA="}

-------------------------------
Environment:
-------------------------------

  * DOCUMENT_ROOT                                  : /home/bmesuere/rails/current/public
  * HTTP_ACCEPT                                    : */*
  * HTTP_ACCEPT_ENCODING                           : gzip, deflate
  * HTTP_ACCEPT_LANGUAGE                           : en-US,en;q=0.5
  * HTTP_CONNECTION                                : keep-alive
  * HTTP_COOKIE                                    : __utma=231869531.89619893.1422351532.1422351532.1422362230.2; __utmz=231869531.1422351532.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); _unipept_web_session=MDl3VHZsc0hyMFNGdk0weUNpamRnamdLLzRJSFduQjk1dmZVbS9QSkJtSWxjMU1pWXRvazVEb0VxOGMzaGhxNU9PSlM3OC9ZL3JOdGNHdUdzTHFqUzhDVGZBSGxvSDRmY0hCU2gzS1hwZmcwdm5SOHhIY2JtdG4waDRhazRzSURBTmhHUkt1djkyZVRhKzhaMUF5ZFhQSEUwMmdET2hWNGZzbGc0ZEF4d1R5Sllpak9QcGlEanpRemhudi8zQmlILS1EU1lsazFEY0h3NW9tVk9jdXAxR0lnPT0%3D--25aaac2fbd8bf0cf2d45aceeebb6d0b173f3dff5; __utmb=231869531.27.9.1422363540937; __utmc=231869531; nonce=0.7009279066794816; __utmt=1
  * HTTP_HOST                                      : unipept.ugent.be
  * HTTP_REFERER                                   : http://unipept.ugent.be/datasets
  * HTTP_USER_AGENT                                : Mozilla/5.0 (X11; Linux x86_64; rv:35.0) Gecko/20100101 Firefox/35.0
  * HTTP_X_CSRF_TOKEN                              : OBrVa1jDt9ojgauiPc92Ass+d67JNthk+Ilh86Ul1qA=
  * HTTP_X_REQUESTED_WITH                          : XMLHttpRequest
  * ORIGINAL_FULLPATH                              : /pride/PXD000054
  * ORIGINAL_SCRIPT_NAME                           :
  * PASSENGER_APP_GROUP_NAME                       : /home/bmesuere/rails/current
  * PASSENGER_APP_ROOT                             : /home/bmesuere/rails/current
  * PASSENGER_APP_TYPE                             : rack
  * PASSENGER_CONNECT_PASSWORD                     : [FILTERED]
  * PASSENGER_DEBUGGER                             : false
  * PASSENGER_FRIENDLY_ERROR_PAGES                 : true
  * PASSENGER_MAX_PRELOADER_IDLE_TIME              : -1
  * PASSENGER_RESTART_DIR                          :
  * PASSENGER_RUBY                                 : /home/bmesuere/.rvm/gems/ruby-2.1.2/wrappers/ruby
  * PASSENGER_SHOW_VERSION_IN_HEADER               : true
  * PASSENGER_SPAWN_METHOD                         : smart
  * PASSENGER_STATUS_LINE                          : false
  * PASSENGER_STAT_THROTTLE_RATE                   : 0
  * PATH_INFO                                      : /pride/PXD000054
  * QUERY_STRING                                   :
  * REMOTE_ADDR                                    : 195.178.203.184
  * REMOTE_PORT                                    : 46325
  * REQUEST_METHOD                                 : GET
  * REQUEST_URI                                    : /pride/PXD000054
  * ROUTES_34053940_SCRIPT_NAME                    :
  * SCRIPT_NAME                                    :
  * SERVER_ADDR                                    : 157.193.230.159
  * SERVER_ADMIN                                   : webmaster`@localhost`
  * SERVER_NAME                                    : unipept.ugent.be
  * SERVER_PORT                                    : 80
  * SERVER_PROTOCOL                                : HTTP/1.1
  * SERVER_SOFTWARE                                : Apache/2.2.22 (Debian)
  * action_controller.instance                     : #<PrideController:0x00000005dc78a0>
  * action_dispatch.backtrace_cleaner              : #<Rails::BacktraceCleaner:0x000000019370a0>
  * action_dispatch.cookies                        : #<ActionDispatch::Cookies::CookieJar:0x00000005dcc8c8>
  * action_dispatch.cookies_serializer             :
  * action_dispatch.encrypted_cookie_salt          : encrypted cookie
  * action_dispatch.encrypted_signed_cookie_salt   : signed encrypted cookie
  * action_dispatch.http_auth_salt                 : http authentication
  * action_dispatch.key_generator                  : #<ActiveSupport::CachingKeyGenerator:0x00000001943170>
  * action_dispatch.logger                         : #<ActiveSupport::Logger:0x00000003fbfd08>
  * action_dispatch.parameter_filter               : [:password]
  * action_dispatch.redirect_filter                : []
  * action_dispatch.remote_ip                      : 195.178.203.184
  * action_dispatch.request.accepts                : [#<Mime::Type:0x00000005dc22b0 `@synonyms`=[], `@symbol`=nil, `@string`="*/*">]
  * action_dispatch.request.content_type           :
  * action_dispatch.request.formats                : [#<Mime::Type:0x00000005dc22b0 `@synonyms`=[], `@symbol`=nil, `@string`="*/*">]
  * action_dispatch.request.parameters             : {"controller"=>"pride", "action"=>"load", "id"=>"PXD000054"}
  * action_dispatch.request.path_parameters        : {:controller=>"pride", :action=>"load", :id=>"PXD000054"}
  * action_dispatch.request.query_parameters       : {}
  * action_dispatch.request.request_parameters     : {}
  * action_dispatch.request.unsigned_session_cookie: {"session_id"=>"68a7b8adcd3b95da7ace9680f4d633e6", "_csrf_token"=>"OBrVa1jDt9ojgauiPc92Ass+d67JNthk+Ilh86Ul1qA="}
  * action_dispatch.request_id                     : 9d03e999-2479-4259-bfcd-277df8c44f29
  * action_dispatch.routes                         : #<ActionDispatch::Routing::RouteSet:0x000000040f3e68>
  * action_dispatch.secret_key_base                : d5e317c34124acdfe97f3d232803a9dfd16d6003624a70cccb35a826c9be8f32a3b72cfef3dd5bf3ce68bfc27eb40490185916ecef55d1d60d8022a40a4884b4
  * action_dispatch.secret_token                   :
  * action_dispatch.show_detailed_exceptions       : false
  * action_dispatch.show_exceptions                : true
  * action_dispatch.signed_cookie_salt             : signed cookie
  * rack.errors                                    : #<IO:0x00000001735c20>
  * rack.hijack                                    : #<Proc:0x00000005dce358@/home/bmesuere/.rvm/gems/ruby-2.1.2/gems/passenger-4.0.44/lib/phusion_passenger/rack/thread_handler_extension.rb:69 (lambda)>
  * rack.hijack?                                   : true
  * rack.input                                     : #<PhusionPassenger::Utils::TeeInput:0x00000005dce538>
  * rack.multiprocess                              : true
  * rack.multithread                               : false
  * rack.request.cookie_hash                       : {"__utma"=>"231869531.89619893.1422351532.1422351532.1422362230.2", "__utmz"=>"231869531.1422351532.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)", "_unipept_web_session"=>"MDl3VHZsc0hyMFNGdk0weUNpamRnamdLLzRJSFduQjk1dmZVbS9QSkJtSWxjMU1pWXRvazVEb0VxOGMzaGhxNU9PSlM3OC9ZL3JOdGNHdUdzTHFqUzhDVGZBSGxvSDRmY0hCU2gzS1hwZmcwdm5SOHhIY2JtdG4waDRhazRzSURBTmhHUkt1djkyZVRhKzhaMUF5ZFhQSEUwMmdET2hWNGZzbGc0ZEF4d1R5Sllpak9QcGlEanpRemhudi8zQmlILS1EU1lsazFEY0h3NW9tVk9jdXAxR0lnPT0=--25aaac2fbd8bf0cf2d45aceeebb6d0b173f3dff5", "__utmb"=>"231869531.27.9.1422363540937", "__utmc"=>"231869531", "nonce"=>"0.7009279066794816", "__utmt"=>"1"}
  * rack.request.cookie_string                     : __utma=231869531.89619893.1422351532.1422351532.1422362230.2; __utmz=231869531.1422351532.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); _unipept_web_session=MDl3VHZsc0hyMFNGdk0weUNpamRnamdLLzRJSFduQjk1dmZVbS9QSkJtSWxjMU1pWXRvazVEb0VxOGMzaGhxNU9PSlM3OC9ZL3JOdGNHdUdzTHFqUzhDVGZBSGxvSDRmY0hCU2gzS1hwZmcwdm5SOHhIY2JtdG4waDRhazRzSURBTmhHUkt1djkyZVRhKzhaMUF5ZFhQSEUwMmdET2hWNGZzbGc0ZEF4d1R5Sllpak9QcGlEanpRemhudi8zQmlILS1EU1lsazFEY0h3NW9tVk9jdXAxR0lnPT0%3D--25aaac2fbd8bf0cf2d45aceeebb6d0b173f3dff5; __utmb=231869531.27.9.1422363540937; __utmc=231869531; nonce=0.7009279066794816; __utmt=1
  * rack.request.query_hash                        : {}
  * rack.request.query_string                      :
  * rack.run_once                                  : false
  * rack.session                                   : #<ActionDispatch::Request::Session:0x00000005dcd020>
  * rack.session.options                           : #<ActionDispatch::Request::Session::Options:0x00000005dccfd0>
  * rack.url_scheme                                : http
  * rack.version                                   : [1, 2]
  * warden                                         : Warden::Proxy:49178420 `@config`={:default_scope=>:user, :scope_defaults=>{}, :default_strategies=>{:user=>[:cas_authenticatable]}, :intercept_401=>false, :failure_app=>#<Devise::Delegator:0x00000002ad2468>}

-------------------------------
Backtrace:
-------------------------------

  app/controllers/pride_controller.rb:4:in `load'
```

_[Original issue](https://github.ugent.be/unipept/unipept/issues/456) by @bmesuere on Tue Jan 27 2015 at 14:09._
_Closed by @bmesuere on Mon Feb 23 2015 at 09:54._

**Comment by bmesuere** [comment]
This was fixed with the implementation of incremental loading.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/456#issuecomment-14018) by @bmesuere on Mon Feb 23 2015 at 09:54._
