### ISSUE TITLE
Pollyfills seem not to work

### ISSUE THREAD

**Issue by beardhatcode** [unipept/unipept#626]
I have opened https://unipept.ugent.be from IE11 on Windows 7 in a VM. According to browserl.ist IE11  is in [`>1%`](http://browserl.ist/?q=%3E1%25)  and [`Last 3 versions`](http://browserl.ist/?q=Last+3+versions) but the polyfills don't seem to work there which is odd.

```
File: mpa
Unhandled promise rejection ReferenceError: 'fetch' is undefined
   "Unhandled promise rejection"
   {
      [functions]: ,
      __proto__: { },
      description: "'fetch' is undefined",
      message: "'fetch' is undefined",
      name: "ReferenceError",
      number: -2146823279,
      stack: "ReferenceError: 'fetch' is undefined
   at value (https://unipept.ugent.be/packs/mpa-4e61964d621b5a0a3371.js:1:55251)
   at Anonymous function (https://unipept.ugent.be/packs/mpa-4e61964d621b5a0a3371.js:1:1608)
   at e (https://unipept.ugent.be/packs/application-1294d4cae2bd5d894a3e.js:1:58607)
   at Anonymous function (https://unipept.ugent.be/packs/application-1294d4cae2bd5d894a3e.js:1:59748)
   at t[n] (https://unipept.ugent.be/packs/application-1294d4cae2bd5d894a3e.js:1:58801)
   at r (https://unipept.ugent.be/packs/mpa-4e61964d621b5a0a3371.js:1:397)
   at Anonymous function (https://unipept.ugent.be/packs/mpa-4e61964d621b5a0a3371.js:1:546)
   at E (https://unipept.ugent.be/packs/application-1294d4cae2bd5d894a3e.js:1:41122)
   at Anonymous function (https://unipept.ugent.be/packs/mpa-4e61964d621b5a0a3371.js:1:344)
   at e (https://unipept.ugent.be/packs/mpa-4e61964d621b5a0a3371.js:1:1271)"
   }
```

It works in chrome on win7 though.

_[Original issue](https://github.ugent.be/unipept/unipept/issues/626) by @beardhatcode on Mon Dec 11 2017 at 14:49._
_Closed by @bmesuere on Mon Dec 11 2017 at 18:41._

**Comment by bmesuere** [comment]
Polyfills do work, but it seems that fetch isn't included in the babel polyfills since it is not a language addition, but a web platform thingy. I'll look into it and deploy a hotfix.

_[Original comment](https://github.ugent.be/unipept/unipept/issues/626#issuecomment-72316) by @bmesuere on Mon Dec 11 2017 at 17:51._

**Comment by bmesuere** [comment]
@beardhatcode Can you check if this is fixed in your browser?

_[Original comment](https://github.ugent.be/unipept/unipept/issues/626#issuecomment-72317) by @bmesuere on Mon Dec 11 2017 at 18:47._

**Comment by beardhatcode** [comment]
resolved
![virtualbox_ie11 - win7_12_12_2017_09_57_21](https://github.ugent.be/storage/user/426/files/d9398f04-df22-11e7-869c-ee9962fd17ca)


_[Original comment](https://github.ugent.be/unipept/unipept/issues/626#issuecomment-72319) by @beardhatcode on Tue Dec 12 2017 at 09:57._
